# Generated by Django 2.2.2 on 2019-10-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20191025_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingprofile',
            name='email',
        ),
    ]
