# Generated by Django 2.2.2 on 2019-10-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='default',
            field=models.BooleanField(default=True),
        ),
    ]
