# Generated by Django 2.2.2 on 2019-10-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('release_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
