# Generated by Django 2.2.2 on 2019-07-14 11:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.TextField(default=datetime.datetime(2019, 7, 14, 11, 13, 15, 174234, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
