# Generated by Django 2.2.2 on 2019-07-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190714_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video',
            new_name='video_url',
        ),
    ]
